config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users

  resources :users, only: [:show, :index] 

  resources :pictures do
   resources :comments, only: [:create, :destroy]
  end  
    
  root to: 'pictures#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
  belongs_to :users
  validates :body, presence: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates :name, :photo, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pictures 
  has_many :comments, through: :pictures      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_picture, only: [:new, :create]
  before_action :authenticate_user! 
  
  def new
  end

  def create
    @comment = @picture.comments.new(comments_params)
    if @comment.save
      redirect_to picture_path(@picture)
    else
      redirect_to :back, notice: 'Comment was not created'
    end
  end

  def destroy
    @comment.destroy
    redirect_to :back, notice: 'Comment was succesfully deleted'
  end

  private

  def comments_params
    params.require(:comment).permit(:body, :picture_id)
  end

  def find_picture
    @picture = Picture.find(params[:picture_id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  def index
    @pictures = Picture.all
  end

  def new
    @picture = current_user.pictures.new
  end

  def create
    @picture = current_user.pictures.new(pictures_params)
    if @picture.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    
  end

  def show
      @picture = Picture.find(params[:id])
      @comment = @picture.comments.build
      @comments = @picture.comments.all  
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to root_url
  end

  private
  def pictures_params
      params.require(:picture).permit(:name, :description, :category, :photo)
  end

end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

 def show
    @user = User.find(params[:id])
    @pictures = @user.pictures
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comments/_form.html.erb
<div class="">

  <% if user_signed_in?  %>
    <%= simple_form_for @comment, url: picture_comments_path(@picture) do |f| %>
      <!-- Check if there were any errors saving project task and display them if so -->
      <% if @comment.errors.any? %>
        <div id='error_explanation'>
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
            this comment from being saved:</h2>
          <ul>
            <% @comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <!-- Begin rendering the form -->
      <h4>Add a comment</h4>
      <div class= 'form-group'>
        <%= f.input :body, label: false, placeholder: "Enter your comment here", input_html: { rows: 4 } %><br>
      </div>

      <p>
        <%= f.submit 'Send', :class => 'button right' %> 
      </p>
    <% end %>
  <% else %>
    <h3> Sign in to create a comment</h3>
  <% end %>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Their Better Half', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <div class="right">
      <ul>
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>  
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'User', user_path(current_user) %></li>
  <li><%= link_to 'Add photo', new_picture_path %></li>  
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tinder" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tinder" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pictures/_form.html.erb
<div class="authform">
  <h3>Upload Photo</h3>
  <%= simple_form_for @picture  do |f| %>
    <!-- Check if there were any errors saving project task and display them if so -->
    <% if @picture.errors.any? %>
      <div id='error_explanation'>
        <h2><%= pluralize(@picture.errors.count, "error") %> prohibited
            this picture from being saved:</h2>
        <ul>
          <% @picture.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Begin rendering the form -->
    <div class= 'form-group'>
      <%= f.input :name %><br>
    </div>

    <div class= 'form-group'>
      <%= f.input :photo %><br>
    </div>

    <div class= 'form-group'>
      <%= f.input :description %><br>
    </div>
   

    <p>
      <%= link_to 'Back', root_path, :class => 'button left' %>
      <%= f.submit 'Submit', :class => 'button right' %> 
    </p>
  <% end %>
</div>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/index.html.erb
<ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
  <% @pictures.each do |picture| %>
    <li><%= link_to image_tag(picture.photo.url(:medium)), picture_path(picture) %></li>
  <% end %>
</ul>

app/views/pictures/new.html.erb
<br>
<%= render 'form' %>

app/views/pictures/show.html.erb
<h1><%= @picture.name %></h1>
<%= image_tag @picture.photo.url(:medium) %>
<h3>Description: <small><%= @picture.description %></small></h3>
<h3>Comments</h3>
<% if @comments.empty? %>
  <h4> No Comments to Display</h4>
<% end %>
<% @comments.each do |comment| %>
<p><%= comment.body %></p>
<% end %>

<%= link_to 'Back', root_path %> 
<% if current_user && @picture.user_id == current_user.id %> 
  <%= link_to 'Delete', @picture, method: :delete, 
                                data: {
                                  confirm: 'Are you sure you want to delete this picture?'} %>
<%end%>

<%= render 'comments/form' %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>